name: DocFX

on:
  repository_dispatch:
    types: [game_version_update]
  push:
    branches:
      - master
      - dev

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  docfx:
    name: DocFX generation
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.x

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Download docfx
      uses: i3h/download-release-asset@v1
      with:
        owner: dotnet
        repo: docfx
        tag: latest
        file: docfx.zip

    - name: Extract docfx
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: docfx.zip
        pathTarget: docfx

    - name: Download latest ref packages
      run: >-
          $stable_version=$env:STABLE_VERSION;
          $stable_version=$stable_version.substring(1);
          $beta_version=$env:BETA_VERSION;
          $beta_version=$beta_version.substring(1);
          dotnet run -p build/PackageDownloader -- `
            -s $stable_version -b $beta_version -n Bannerlord.ReferenceAssemblies `
            -t $PWD `
            -f https://nuget.pkg.github.com/BUTR/index.json -u Aragas -p ${{secrets.GITHUB_TOKEN}}
      shell: pwsh
      env:
        STABLE_VERSION: ${{secrets.SYNCED_GAME_STABLE_VERSION}}
        BETA_VERSION: ${{secrets.SYNCED_GAME_BETA_VERSION}}

    - name: Generate Newtonsoft.Json xref maps
      run: >-
        dotnet run -p build/SandcastleXrefGenerator -- `
            Newtonsoft.Json 11.0.2 netstandard2.0 `
            https://www.newtonsoft.com/json/help/html/ `
            $PWD/docs/xrefs/Newtonsoft.Json-xrefmap.yml
      shell: pwsh

    - name: Build DocFx.Plugin.LastModified
      run: dotnet build build/DocFx.Plugin.LastModified/DocFx.Plugin.LastModified --configuration Release --output docs/_template/last-modified/plugins
      shell: pwsh

    - name: DocFX metadata
      run: >-
        docfx/docfx.exe metadata docs/docfx-meta-stable.json;
      env:
        DOCFX: true

    - name: DocFX build
      run: docfx/docfx.exe build docs/docfx-build.json;

    - name: Deploy DocFX
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: docs/_site
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
